### ISSUE TITLE
Update the Social Links of Team

### ISSUE THREAD

**Issue by XFarooqi** [Ahmad44452/comsatshackathon#1]
The majority of the team members' social links are either broken or give a 404 error. We need to update those social links.

[This Link Contains Updated Social Info](https://docs.google.com/spreadsheets/d/1KwIY-glGYA0949qnqQHN42LIhMnWKIoGxqQbtq5Rd6Y/edit?usp=sharing)

Moreover, there are new leads in this cohort, Daniyal and Ali Sajjad. We need to add them as well.

**Comment by Ahmad44452** [comment]
All the required changes have been made.
